spring.application.name=pos-papeleria


# ==========================================
# CONEXIÓN A BASE DE DATOS MARIADB
# ==========================================
spring.datasource.url=jdbc:mariadb://localhost:3306/pos_papeleria
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ==========================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ==========================================
# Usamos 'validate' porque las tablas ya las creamos a mano con precisión.
# Esto evitará que Hibernate destruya o modifique nuestra estructura SQL.
spring.jpa.hibernate.ddl-auto=validate

# Mostramos el SQL en la consola para ayudarte a depurar (muy útil como Junior)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto específico para MariaDB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# ==========================================
# CONFIGURACIÓN DEL SERVIDOR WEB
# ==========================================
server.port=8080


# --- CONFIGURACIÓN DE CORREO (GMAIL SMTP) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=papelerialacolonial29@gmail.com
# Aquí va la contraseña de 16 caracteres generada en Google (App Passwords), NO la clave normal
spring.mail.password=lhsa deou ngoi msbw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true